
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "IBanqueService", targetNamespace = "http://example.org/", wsdlLocation = "http://localhost:8085/?wsdl")
public class IBanqueService
    extends Service
{

    private static final URL IBANQUESERVICE_WSDL_LOCATION;
    private static final WebServiceException IBANQUESERVICE_EXCEPTION;
    private static final QName IBANQUESERVICE_QNAME = new QName("http://example.org/", "IBanqueService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IBANQUESERVICE_WSDL_LOCATION = url;
        IBANQUESERVICE_EXCEPTION = e;
    }

    public IBanqueService() {
        super(__getWsdlLocation(), IBANQUESERVICE_QNAME);
    }

    public IBanqueService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IBANQUESERVICE_QNAME, features);
    }

    public IBanqueService(URL wsdlLocation) {
        super(wsdlLocation, IBANQUESERVICE_QNAME);
    }

    public IBanqueService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IBANQUESERVICE_QNAME, features);
    }

    public IBanqueService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IBanqueService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BanqueService
     */
    @WebEndpoint(name = "BanqueServicePort")
    public BanqueService getBanqueServicePort() {
        return super.getPort(new QName("http://example.org/", "BanqueServicePort"), BanqueService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BanqueService
     */
    @WebEndpoint(name = "BanqueServicePort")
    public BanqueService getBanqueServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.org/", "BanqueServicePort"), BanqueService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IBANQUESERVICE_EXCEPTION!= null) {
            throw IBANQUESERVICE_EXCEPTION;
        }
        return IBANQUESERVICE_WSDL_LOCATION;
    }

}
